### ISSUE TITLE
information not fetched from cookie

### ISSUE THREAD

**Issue by 10thfloor** [j-forsythe/red-project4-angularjs#1]
<img width="688" alt="screen shot 2016-03-11 at 11 38 55" src="https://cloud.githubusercontent.com/assets/901466/13713467/f1d636e6-e77d-11e5-8465-9b45cd5e0c08.png">

Here, when assigning to the name property, `$cookies.getObject('mars_cookie')` returns undefined, resulting in your app crashing...

```
$rootScope.userInfo = {
     name: $cookies.getObject('mars_cookie').name,
     job: $cookies.getObject('mars_cookie').job.name
};
```

**Comment by j-forsythe** [comment]
Added userInfo cookie information to report controller to stop app from crashing.
